- name: development/base | Install the required packages
  dnf:
    name: [
      'zeromq-devel',
      'fedpkg',
      'fedora-packager',
      'redhat-rpm-config',
      'libxslt-devel',
      'htop',
      'vagrant',
      'vagrant-libvirt'
    ]
    state: installed
  become: true
  become_method: sudo
  tags:
  - development
