---
- name: neovim | install neovim
  become: yes
  dnf:
    name: "{{ item }}"
    state: installed
  with_items:
    - neovim
  tags:
  - application
  - nvim

- name: neovim | stow neovim
  command: stow neovim
    chdir: "{{ ansible_env.HOME }}/dotfiles"

- name: neovim | install the neovim plugins
  command: nvim +PlugInstall +qall
  tags:
  - application
  - nvim
