---
- name: nginx configuration for the tldr box
  become: true
  template:
    src: nginx-http.conf.j2
    dest: /etc/nginx/conf.d/nginx-http.conf
  notify:
    - restart nginx
  tags:
    - host
    - tldr-yudocaa

- name: Create the directory structure
  become: true
  file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ g_user }}"
    group: "{{ g_user }}"
    mode: "{{ item.mode }}"
  with_items:
    - {path: "{{ tldr_yudocaa_basedir }}", mode: 755}
  tags:
    - host
    - tldr-yudocaa
    - structure

- name: clone the repository from github
  git:
    repo: https://github.com/sayanchowdhury/tldr.yudocaa.in.git
    dest: /srv/tldr-yudocaa
    update: no
  tags:
    - host
    - tldr-yudocaa

