- name: Install the cerbot package
  dnf:
    name: "{{ item }}"
    state: "present"
  with_items:
    - certbot

- name: Setup a cron to renew
  cron:
    name: "certbot-renew"
    special_time: "monthly"
    job: "cert
