- name: Install the required packages
  dnf:
    name: "{{ item }}"
    state: present
  become: true
  become_method: sudo
  with_items:
  - git
  - gitflow
  - hub
  - python-virtualenvwrapper
  - python-pip
  - gcc
  - gcc-c++
  - libcurl-devel
  - libffi-devel
  - zeromq-devel
  - fedpkg
  - fedora-packager
  - redhat-rpm-config
  - libxslt-devel # For building lxml in venv
  tags:
  - development

- name: Synchromize scripts to /usr/local/bin
  synchronize:
    src: bin/
    dest: /usr/local/bin/
  tags:
  - development
