---
- name: Install python2-dnf package for ansible to work
  sudo: yes
  raw: dnf -y install python2-dnf
  tags:
    - base
    - dnf

- name: Install the required packages
  dnf:
    name: [
      'gcc',
      'gcc-c++',
      'git',
      'libcurl-devel',
      'libffi-devel',
      'libselinux-python',
      'python-pip',
      'python-virtualenvwrapper',
      'stow'
    ]
    state: present
  become: true
  become_method: sudo
  tags:
  - base
  - install
