---
- name: Install python2-dnf package for ansible to work
  sudo: yes
  raw: dnf -y install python2-dnf
  tags:
    - base
    - dnf

- name: Install the default base packages
  sudo: yes
  dnf:
    name: "{{ item }}"
    state: "installed"
  with_items:
    - libselinux-python
