---

- name: git | install git
  dnf:
    name: [
      'git'
    ]
    state: installed
  become: yes
  become_method: sudo
  tags:
  - application
  - git

- name: git | stow git
  command: stow git
    chdir: {{ ansible.HOME }}/dotfiles
  tags:
  - application
  - git
