---

- name: System Configuration (packages, etc)
  hosts: laptop

  roles:
  - development
  tags:
  - development

- name: Install Applications on this Laptop along with configurations
  hosts: laptop
  roles:
  - applications/git
  - applications/neovim
  - applications/zsh
  - applications/zim
  tags:
  - application
