---

- name: System Configuration (packages, etc)
  hosts: all

  roles:
  - development
  tags:
  - development

- name: Instal Applications on this Laptop along with configurations
  hosts: devbox
  roles:
  - applications/git
  - applications/neovim
  - applications/zsh
  - applications/zim
  tags:
  - application
